package com.kf.data.mybatis.entity;

public class UserFriend {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_user_friend.id
     *
     * @mbggenerated Wed Apr 04 16:24:01 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_user_friend.user_id
     *
     * @mbggenerated Wed Apr 04 16:24:01 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_user_friend.friend_id
     *
     * @mbggenerated Wed Apr 04 16:24:01 CST 2018
     */
    private Integer friendId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_user_friend.group_id
     *
     * @mbggenerated Wed Apr 04 16:24:01 CST 2018
     */
    private Integer groupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_user_friend.id
     *
     * @return the value of im_user_friend.id
     *
     * @mbggenerated Wed Apr 04 16:24:01 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_user_friend.id
     *
     * @param id the value for im_user_friend.id
     *
     * @mbggenerated Wed Apr 04 16:24:01 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_user_friend.user_id
     *
     * @return the value of im_user_friend.user_id
     *
     * @mbggenerated Wed Apr 04 16:24:01 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_user_friend.user_id
     *
     * @param userId the value for im_user_friend.user_id
     *
     * @mbggenerated Wed Apr 04 16:24:01 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_user_friend.friend_id
     *
     * @return the value of im_user_friend.friend_id
     *
     * @mbggenerated Wed Apr 04 16:24:01 CST 2018
     */
    public Integer getFriendId() {
        return friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_user_friend.friend_id
     *
     * @param friendId the value for im_user_friend.friend_id
     *
     * @mbggenerated Wed Apr 04 16:24:01 CST 2018
     */
    public void setFriendId(Integer friendId) {
        this.friendId = friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_user_friend.group_id
     *
     * @return the value of im_user_friend.group_id
     *
     * @mbggenerated Wed Apr 04 16:24:01 CST 2018
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_user_friend.group_id
     *
     * @param groupId the value for im_user_friend.group_id
     *
     * @mbggenerated Wed Apr 04 16:24:01 CST 2018
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }
}