package com.kf.data.mybatis.entity;

import java.util.Date;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column im_user.id
	 * @mbggenerated  Wed Apr 04 16:23:22 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column im_user.sso_id
	 * @mbggenerated  Wed Apr 04 16:23:22 CST 2018
	 */
	private String ssoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column im_user.password
	 * @mbggenerated  Wed Apr 04 16:23:22 CST 2018
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column im_user.create_time
	 * @mbggenerated  Wed Apr 04 16:23:22 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column im_user.last_login_time
	 * @mbggenerated  Wed Apr 04 16:23:22 CST 2018
	 */
	private Date lastLoginTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column im_user.user_status
	 * @mbggenerated  Wed Apr 04 16:23:22 CST 2018
	 */
	private Integer userStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column im_user.avatar
	 * @mbggenerated  Wed Apr 04 16:23:22 CST 2018
	 */
	private String avatar;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column im_user.email
	 * @mbggenerated  Wed Apr 04 16:23:22 CST 2018
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column im_user.phone
	 * @mbggenerated  Wed Apr 04 16:23:22 CST 2018
	 */
	private Integer phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column im_user.user_name
	 * @mbggenerated  Wed Apr 04 16:23:22 CST 2018
	 */
	private String userName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column im_user.id
	 * @return  the value of im_user.id
	 * @mbggenerated  Wed Apr 04 16:23:22 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column im_user.id
	 * @param id  the value for im_user.id
	 * @mbggenerated  Wed Apr 04 16:23:22 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column im_user.sso_id
	 * @return  the value of im_user.sso_id
	 * @mbggenerated  Wed Apr 04 16:23:22 CST 2018
	 */
	public String getSsoId() {
		return ssoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column im_user.sso_id
	 * @param ssoId  the value for im_user.sso_id
	 * @mbggenerated  Wed Apr 04 16:23:22 CST 2018
	 */
	public void setSsoId(String ssoId) {
		this.ssoId = ssoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column im_user.password
	 * @return  the value of im_user.password
	 * @mbggenerated  Wed Apr 04 16:23:22 CST 2018
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column im_user.password
	 * @param password  the value for im_user.password
	 * @mbggenerated  Wed Apr 04 16:23:22 CST 2018
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column im_user.create_time
	 * @return  the value of im_user.create_time
	 * @mbggenerated  Wed Apr 04 16:23:22 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column im_user.create_time
	 * @param createTime  the value for im_user.create_time
	 * @mbggenerated  Wed Apr 04 16:23:22 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column im_user.last_login_time
	 * @return  the value of im_user.last_login_time
	 * @mbggenerated  Wed Apr 04 16:23:22 CST 2018
	 */
	public Date getLastLoginTime() {
		return lastLoginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column im_user.last_login_time
	 * @param lastLoginTime  the value for im_user.last_login_time
	 * @mbggenerated  Wed Apr 04 16:23:22 CST 2018
	 */
	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column im_user.user_status
	 * @return  the value of im_user.user_status
	 * @mbggenerated  Wed Apr 04 16:23:22 CST 2018
	 */
	public Integer getUserStatus() {
		return userStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column im_user.user_status
	 * @param userStatus  the value for im_user.user_status
	 * @mbggenerated  Wed Apr 04 16:23:22 CST 2018
	 */
	public void setUserStatus(Integer userStatus) {
		this.userStatus = userStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column im_user.avatar
	 * @return  the value of im_user.avatar
	 * @mbggenerated  Wed Apr 04 16:23:22 CST 2018
	 */
	public String getAvatar() {
		return avatar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column im_user.avatar
	 * @param avatar  the value for im_user.avatar
	 * @mbggenerated  Wed Apr 04 16:23:22 CST 2018
	 */
	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column im_user.email
	 * @return  the value of im_user.email
	 * @mbggenerated  Wed Apr 04 16:23:22 CST 2018
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column im_user.email
	 * @param email  the value for im_user.email
	 * @mbggenerated  Wed Apr 04 16:23:22 CST 2018
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column im_user.phone
	 * @return  the value of im_user.phone
	 * @mbggenerated  Wed Apr 04 16:23:22 CST 2018
	 */
	public Integer getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column im_user.phone
	 * @param phone  the value for im_user.phone
	 * @mbggenerated  Wed Apr 04 16:23:22 CST 2018
	 */
	public void setPhone(Integer phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column im_user.user_name
	 * @return  the value of im_user.user_name
	 * @mbggenerated  Wed Apr 04 16:23:22 CST 2018
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column im_user.user_name
	 * @param userName  the value for im_user.user_name
	 * @mbggenerated  Wed Apr 04 16:23:22 CST 2018
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}
}