package com.kf.data.mybatis.entity;

import java.util.Date;

public class UserGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_user_group.id
     *
     * @mbggenerated Sun Apr 08 14:31:29 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_user_group.group_name
     *
     * @mbggenerated Sun Apr 08 14:31:29 CST 2018
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_user_group.group_status
     *
     * @mbggenerated Sun Apr 08 14:31:29 CST 2018
     */
    private Integer groupStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_user_group.create_id
     *
     * @mbggenerated Sun Apr 08 14:31:29 CST 2018
     */
    private Integer createId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_user_group.create_time
     *
     * @mbggenerated Sun Apr 08 14:31:29 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_user_group.avatar
     *
     * @mbggenerated Sun Apr 08 14:31:29 CST 2018
     */
    private String avatar;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_user_group.id
     *
     * @return the value of im_user_group.id
     *
     * @mbggenerated Sun Apr 08 14:31:29 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_user_group.id
     *
     * @param id the value for im_user_group.id
     *
     * @mbggenerated Sun Apr 08 14:31:29 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_user_group.group_name
     *
     * @return the value of im_user_group.group_name
     *
     * @mbggenerated Sun Apr 08 14:31:29 CST 2018
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_user_group.group_name
     *
     * @param groupName the value for im_user_group.group_name
     *
     * @mbggenerated Sun Apr 08 14:31:29 CST 2018
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_user_group.group_status
     *
     * @return the value of im_user_group.group_status
     *
     * @mbggenerated Sun Apr 08 14:31:29 CST 2018
     */
    public Integer getGroupStatus() {
        return groupStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_user_group.group_status
     *
     * @param groupStatus the value for im_user_group.group_status
     *
     * @mbggenerated Sun Apr 08 14:31:29 CST 2018
     */
    public void setGroupStatus(Integer groupStatus) {
        this.groupStatus = groupStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_user_group.create_id
     *
     * @return the value of im_user_group.create_id
     *
     * @mbggenerated Sun Apr 08 14:31:29 CST 2018
     */
    public Integer getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_user_group.create_id
     *
     * @param createId the value for im_user_group.create_id
     *
     * @mbggenerated Sun Apr 08 14:31:29 CST 2018
     */
    public void setCreateId(Integer createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_user_group.create_time
     *
     * @return the value of im_user_group.create_time
     *
     * @mbggenerated Sun Apr 08 14:31:29 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_user_group.create_time
     *
     * @param createTime the value for im_user_group.create_time
     *
     * @mbggenerated Sun Apr 08 14:31:29 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_user_group.avatar
     *
     * @return the value of im_user_group.avatar
     *
     * @mbggenerated Sun Apr 08 14:31:29 CST 2018
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_user_group.avatar
     *
     * @param avatar the value for im_user_group.avatar
     *
     * @mbggenerated Sun Apr 08 14:31:29 CST 2018
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }
}