package com.kf.data.mybatis.mapper;

import com.kf.data.mybatis.entity.NeeqCompanyNoticeCrawler;
import com.kf.data.mybatis.entity.NeeqCompanyNoticeCrawlerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NeeqCompanyNoticeCrawlerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_notice
     *
     * @mbggenerated Mon Mar 05 14:40:02 CST 2018
     */
    int countByExample(NeeqCompanyNoticeCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_notice
     *
     * @mbggenerated Mon Mar 05 14:40:02 CST 2018
     */
    int deleteByExample(NeeqCompanyNoticeCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_notice
     *
     * @mbggenerated Mon Mar 05 14:40:02 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_notice
     *
     * @mbggenerated Mon Mar 05 14:40:02 CST 2018
     */
    int insert(NeeqCompanyNoticeCrawler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_notice
     *
     * @mbggenerated Mon Mar 05 14:40:02 CST 2018
     */
    int insertSelective(NeeqCompanyNoticeCrawler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_notice
     *
     * @mbggenerated Mon Mar 05 14:40:02 CST 2018
     */
    List<NeeqCompanyNoticeCrawler> selectByExample(NeeqCompanyNoticeCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_notice
     *
     * @mbggenerated Mon Mar 05 14:40:02 CST 2018
     */
    NeeqCompanyNoticeCrawler selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_notice
     *
     * @mbggenerated Mon Mar 05 14:40:02 CST 2018
     */
    int updateByExampleSelective(@Param("record") NeeqCompanyNoticeCrawler record, @Param("example") NeeqCompanyNoticeCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_notice
     *
     * @mbggenerated Mon Mar 05 14:40:02 CST 2018
     */
    int updateByExample(@Param("record") NeeqCompanyNoticeCrawler record, @Param("example") NeeqCompanyNoticeCrawlerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_notice
     *
     * @mbggenerated Mon Mar 05 14:40:02 CST 2018
     */
    int updateByPrimaryKeySelective(NeeqCompanyNoticeCrawler record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neeq_company_notice
     *
     * @mbggenerated Mon Mar 05 14:40:02 CST 2018
     */
    int updateByPrimaryKey(NeeqCompanyNoticeCrawler record);
}