package com.kf.data.mybatis.mapper;

import com.kf.data.mybatis.entity.UserGroup;
import com.kf.data.mybatis.entity.UserGroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_user_group
     *
     * @mbggenerated Sun Apr 08 14:31:29 CST 2018
     */
    int countByExample(UserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_user_group
     *
     * @mbggenerated Sun Apr 08 14:31:29 CST 2018
     */
    int deleteByExample(UserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_user_group
     *
     * @mbggenerated Sun Apr 08 14:31:29 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_user_group
     *
     * @mbggenerated Sun Apr 08 14:31:29 CST 2018
     */
    int insert(UserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_user_group
     *
     * @mbggenerated Sun Apr 08 14:31:29 CST 2018
     */
    int insertSelective(UserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_user_group
     *
     * @mbggenerated Sun Apr 08 14:31:29 CST 2018
     */
    List<UserGroup> selectByExample(UserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_user_group
     *
     * @mbggenerated Sun Apr 08 14:31:29 CST 2018
     */
    UserGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_user_group
     *
     * @mbggenerated Sun Apr 08 14:31:29 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserGroup record, @Param("example") UserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_user_group
     *
     * @mbggenerated Sun Apr 08 14:31:29 CST 2018
     */
    int updateByExample(@Param("record") UserGroup record, @Param("example") UserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_user_group
     *
     * @mbggenerated Sun Apr 08 14:31:29 CST 2018
     */
    int updateByPrimaryKeySelective(UserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_user_group
     *
     * @mbggenerated Sun Apr 08 14:31:29 CST 2018
     */
    int updateByPrimaryKey(UserGroup record);
}