package com.kf.data.mybatis.mapper;

import com.kf.data.mybatis.entity.UserProfile;
import com.kf.data.mybatis.entity.UserProfileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserProfileMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table im_user_profile
	 * @mbggenerated  Wed Apr 04 16:23:42 CST 2018
	 */
	int countByExample(UserProfileExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table im_user_profile
	 * @mbggenerated  Wed Apr 04 16:23:42 CST 2018
	 */
	int deleteByExample(UserProfileExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table im_user_profile
	 * @mbggenerated  Wed Apr 04 16:23:42 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table im_user_profile
	 * @mbggenerated  Wed Apr 04 16:23:42 CST 2018
	 */
	int insert(UserProfile record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table im_user_profile
	 * @mbggenerated  Wed Apr 04 16:23:42 CST 2018
	 */
	int insertSelective(UserProfile record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table im_user_profile
	 * @mbggenerated  Wed Apr 04 16:23:42 CST 2018
	 */
	List<UserProfile> selectByExample(UserProfileExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table im_user_profile
	 * @mbggenerated  Wed Apr 04 16:23:42 CST 2018
	 */
	UserProfile selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table im_user_profile
	 * @mbggenerated  Wed Apr 04 16:23:42 CST 2018
	 */
	int updateByExampleSelective(@Param("record") UserProfile record, @Param("example") UserProfileExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table im_user_profile
	 * @mbggenerated  Wed Apr 04 16:23:42 CST 2018
	 */
	int updateByExample(@Param("record") UserProfile record, @Param("example") UserProfileExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table im_user_profile
	 * @mbggenerated  Wed Apr 04 16:23:42 CST 2018
	 */
	int updateByPrimaryKeySelective(UserProfile record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table im_user_profile
	 * @mbggenerated  Wed Apr 04 16:23:42 CST 2018
	 */
	int updateByPrimaryKey(UserProfile record);
}