package com.kf.data.mybatis.mapper;

import com.kf.data.mybatis.entity.UserFriend;
import com.kf.data.mybatis.entity.UserFriendExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserFriendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_user_friend
     *
     * @mbggenerated Wed Apr 04 16:24:01 CST 2018
     */
    int countByExample(UserFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_user_friend
     *
     * @mbggenerated Wed Apr 04 16:24:01 CST 2018
     */
    int deleteByExample(UserFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_user_friend
     *
     * @mbggenerated Wed Apr 04 16:24:01 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_user_friend
     *
     * @mbggenerated Wed Apr 04 16:24:01 CST 2018
     */
    int insert(UserFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_user_friend
     *
     * @mbggenerated Wed Apr 04 16:24:01 CST 2018
     */
    int insertSelective(UserFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_user_friend
     *
     * @mbggenerated Wed Apr 04 16:24:01 CST 2018
     */
    List<UserFriend> selectByExample(UserFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_user_friend
     *
     * @mbggenerated Wed Apr 04 16:24:01 CST 2018
     */
    UserFriend selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_user_friend
     *
     * @mbggenerated Wed Apr 04 16:24:01 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserFriend record, @Param("example") UserFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_user_friend
     *
     * @mbggenerated Wed Apr 04 16:24:01 CST 2018
     */
    int updateByExample(@Param("record") UserFriend record, @Param("example") UserFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_user_friend
     *
     * @mbggenerated Wed Apr 04 16:24:01 CST 2018
     */
    int updateByPrimaryKeySelective(UserFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table im_user_friend
     *
     * @mbggenerated Wed Apr 04 16:24:01 CST 2018
     */
    int updateByPrimaryKey(UserFriend record);
}